<a href="https://colab.research.google.com/github/Bhawnadhaka/Gen--AI-Learning/blob/main/Reranking_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
documents=[
    "The quick brown fox jumps over the lazy dog.",
    "This is the second line of text.",
    "Another line added for demonstration purposes.",
    "We are adding multiple lines to the list.",
    "This list will contain a few sample sentences.",
    "Just a few more lines to reach the desired count.",
    "This is the seventh line.",
    "And finally, the eighth line."
]

In [2]:
!pip install sentence_transformers

In [1]:
from sentence_transformers import SentenceTransformer

In [2]:
model_name='sentence-transformers/paraphrase-xlm-r-multilingual-v1'

In [3]:
model=SentenceTransformer(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
document_embeddings=model.encode(documents)

In [8]:
len(document_embeddings)

8

In [9]:
for i, embedding in enumerate(document_embeddings):
  print(f"Document {i + 1}")
  print(f"Embedding: {embedding}")


Document 1
Embedding: [-8.01067799e-02  1.85940817e-01  1.78719103e-01 -3.54557097e-01
 -4.04086709e-02 -3.05850338e-02 -1.57927200e-01  1.92163527e-01
  3.21924150e-01  1.72924995e-01 -1.37070179e-01 -2.83143949e-02
  1.54160246e-01  1.21758096e-01 -1.81885779e-01 -3.70372623e-01
  2.15152472e-01 -1.70715526e-01 -9.81844142e-02  2.91833937e-01
 -1.19702376e-01 -2.16017947e-01  1.34872586e-01 -2.84418523e-01
  4.68888171e-02  1.69166759e-01 -3.07623833e-01  2.57485569e-01
 -4.15442556e-01  5.26802726e-02 -5.18155135e-02 -5.87346777e-02
 -6.65510893e-02  2.92713344e-01  1.41736761e-01 -4.71297130e-02
  1.45669743e-01  6.47689030e-02  2.00953409e-02 -3.32663804e-02
 -1.56658202e-01 -1.23771347e-01  1.99945923e-02  1.46273181e-01
  2.25059744e-02  3.42641659e-02  7.30632693e-02 -1.23916164e-01
 -4.06539924e-02  1.57120720e-01  4.17622104e-02 -1.16548948e-01
 -6.32045120e-02 -2.88082182e-01  4.89774300e-03  2.46080324e-01
  2.15347484e-02 -2.37810150e-01  1.35626554e-01  4.21071015e-02
 -1

In [10]:
query = "What is mentioned in the initial lines of the document?"

In [11]:
query_embeddings=model.encode(query)

In [13]:
print("Query embedding:", query_embeddings)

Query embedding: [ 2.32881561e-01  3.70785221e-02 -2.82201171e-02 -1.24035284e-01
  4.03259136e-02  3.72492373e-01 -1.22232474e-01  5.91790020e-01
  3.12765330e-01 -3.37489665e-01  9.67870280e-02 -7.37585574e-02
  9.10046622e-02 -4.38089147e-02  3.09027195e-01 -5.02132960e-02
  5.17096400e-01  1.38149962e-01 -5.94390593e-02  3.37548614e-01
 -1.24847136e-01 -6.91853389e-02 -1.63196012e-01 -1.80108547e-01
 -2.22040832e-01  1.65694565e-01 -1.45708159e-01 -1.06761746e-01
 -7.95441717e-02  1.22267298e-01  9.10920799e-02  1.52606785e-01
 -3.13991196e-02 -1.75897494e-01 -5.06053045e-02  3.65006700e-02
  1.75992418e-02 -1.49106488e-01 -5.12976944e-01  3.03961724e-01
  3.14267240e-02  4.20456707e-01 -3.51845950e-01  2.23979697e-01
 -2.71483436e-02  1.19092345e-01  4.83160205e-02 -7.21839905e-01
  3.17837298e-02 -6.08595833e-02  2.43587390e-01 -8.84168521e-02
  4.41039056e-01  2.13277444e-01  1.24312826e-01 -2.49890350e-02
  9.66782961e-03 -1.33262306e-01 -4.96538132e-02  3.17350358e-01
 -1.1708

In [14]:
len(query_embeddings)

768

In [16]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
similarities=cosine_similarity(np.array([query_embeddings]),document_embeddings)

In [20]:
similarities

array([[0.00592898, 0.45279056, 0.30114752, 0.35136983, 0.30046162,
        0.2009407 , 0.25197196, 0.23106444]], dtype=float32)

In [22]:
most_similar_index=np.argmax(similarities)

In [23]:
most_similar_index

np.int64(1)

In [24]:
most_similar_document=documents[most_similar_index]

In [25]:
most_similar_document

'This is the second line of text.'

In [26]:
query

'What is mentioned in the initial lines of the document?'

In [27]:
sorted_indices=np.argsort(similarities[0])[::-1]

In [28]:
sorted_indices

array([1, 3, 2, 4, 6, 7, 5, 0])

In [29]:
ranked_documents=[(documents[i],similarities[0][i]) for i in sorted_indices]

In [31]:
ranked_documents

[('This is the second line of text.', np.float32(0.45279056)),
 ('We are adding multiple lines to the list.', np.float32(0.35136983)),
 ('Another line added for demonstration purposes.', np.float32(0.30114752)),
 ('This list will contain a few sample sentences.', np.float32(0.30046162)),
 ('This is the seventh line.', np.float32(0.25197196)),
 ('And finally, the eighth line.', np.float32(0.23106444)),
 ('Just a few more lines to reach the desired count.', np.float32(0.2009407)),
 ('The quick brown fox jumps over the lazy dog.', np.float32(0.0059289783))]

In [32]:
print("Ranked Documents:")
for rank , (document , similarity) in enumerate (ranked_documents , start=1):
  print(f"Rank {rank}:Document - '{document}' , similarity score - {similarity}")

Ranked Documents:
Rank 1:Document - 'This is the second line of text.' , similarity score - 0.4527905583381653
Rank 2:Document - 'We are adding multiple lines to the list.' , similarity score - 0.35136982798576355
Rank 3:Document - 'Another line added for demonstration purposes.' , similarity score - 0.3011475205421448
Rank 4:Document - 'This list will contain a few sample sentences.' , similarity score - 0.30046162009239197
Rank 5:Document - 'This is the seventh line.' , similarity score - 0.251971960067749
Rank 6:Document - 'And finally, the eighth line.' , similarity score - 0.23106443881988525
Rank 7:Document - 'Just a few more lines to reach the desired count.' , similarity score - 0.20094069838523865
Rank 8:Document - 'The quick brown fox jumps over the lazy dog.' , similarity score - 0.005928978323936462


In [33]:
print("Top 4 Documents :")
for rank , (document ,similarity ) in enumerate(ranked_documents[:4] , start=1):
  print(f"Rank {rank}:Document - '{document}' , similarity score - {similarity}")

Top 4 Documents :
Rank 1:Document - 'This is the second line of text.' , similarity score - 0.4527905583381653
Rank 2:Document - 'We are adding multiple lines to the list.' , similarity score - 0.35136982798576355
Rank 3:Document - 'Another line added for demonstration purposes.' , similarity score - 0.3011475205421448
Rank 4:Document - 'This list will contain a few sample sentences.' , similarity score - 0.30046162009239197


In [34]:
!pip install rank_bm25

In [35]:
top_4_documents=[doc[0] for doc in ranked_documents[:4]]

In [36]:
top_4_documents

['This is the second line of text.',
 'We are adding multiple lines to the list.',
 'Another line added for demonstration purposes.',
 'This list will contain a few sample sentences.']

In [37]:
tokenized_top4_documents=[doc.split() for doc in top_4_documents]

In [38]:
tokenized_top4_documents

[['This', 'is', 'the', 'second', 'line', 'of', 'text.'],
 ['We', 'are', 'adding', 'multiple', 'lines', 'to', 'the', 'list.'],
 ['Another', 'line', 'added', 'for', 'demonstration', 'purposes.'],
 ['This', 'list', 'will', 'contain', 'a', 'few', 'sample', 'sentences.']]

In [40]:
tokenized_query=query.split()

In [41]:
tokenized_query

['What',
 'is',
 'mentioned',
 'in',
 'the',
 'initial',
 'lines',
 'of',
 'the',
 'document?']

In [46]:
from rank_bm25 import BM25Okapi

In [45]:
bm25=BM25Okapi(tokenized_top4_documents)

In [47]:
bm25_score=bm25.get_scores(tokenized_query)

In [48]:
bm25_score

array([1.72130564, 0.80960916, 0.        , 0.        ])

In [50]:
sorted_indices2=np.argsort(bm25_score)[::-1]

In [51]:
sorted_indices2

array([0, 1, 2, 3])

In [52]:
top_4_documents

['This is the second line of text.',
 'We are adding multiple lines to the list.',
 'Another line added for demonstration purposes.',
 'This list will contain a few sample sentences.']

In [53]:
reranked_documents = [(top_4_documents[i], bm25_score[i]) for i in sorted_indices2]

In [54]:
reranked_documents

['This is the second line of text.',
 'We are adding multiple lines to the list.',
 'Another line added for demonstration purposes.',
 'This list will contain a few sample sentences.']

In [57]:
reranked_documents

['This is the second line of text.',
 'We are adding multiple lines to the list.',
 'Another line added for demonstration purposes.',
 'This list will contain a few sample sentences.']